title: Dr. Vedant Basu
email: vbasu@icecube.wisc.edu
description: >-
  Professional website for Dr. Vedant Basu, neutrino astrophysicist.
baseurl: "/docs"
url: "https://vedant8.github.io"
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

markdown: GFM

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
