title: Dr. Vedant Basu
email: vbasu@icecube.wisc.edu
description: >-
  Professional website for Dr. Vedant Basu, neutrino astrophysicist.
baseurl: "/docs"
url: "https://vedant8.github.io"
github_username: vedant8

markdown: GFM
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

nav:
  - title: Home
    url: /docs/
  - title: About
    url: /docs/about/

sass:
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      css: "/docs/assets/css/custom.css"
