name: Build and Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is 'master'

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          cd docs
          gem install bundler
          bundle install

      - name: Build site
        run: |
          cd docs
          bundle exec jekyll build --destination ../_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
